cacheFolder: ./.yarn/cache

cloneConcurrency: 5

enableGlobalCache: false

enableTelemetry: false

defaultSemverRangePrefix: ''

logFilters:
    - code: YN0013
      level: discard
    - code: YN0007
      level: discard

nodeLinker: pnp

plugins:
    - path: .yarn/plugins/@yarnpkg/plugin-engines.cjs
      spec: 'https://raw.githubusercontent.com/devoto13/yarn-plugin-engines/main/bundles/%40yarnpkg/plugin-engines.js'
